package com.example.admin.role.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import java.time.LocalDateTime;

/**
 * Role database entity.
 *
 * Entity means a Java object that maps to one database table. This class maps
 * to the sys_role table, and each RoleEntity object represents one row.
 */
@Entity
@Table(name = "sys_role")
public class RoleEntity {

    /**
     * Primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Stable role code used by APIs and program logic.
     *
     * Example: super_admin, operator, readonly.
     */
    @Column(nullable = false, unique = true, length = 50)
    private String code;

    /**
     * Role name displayed on the frontend page.
     */
    @Column(nullable = false, length = 50)
    private String name;

    /**
     * Human-readable role description.
     */
    @Column(nullable = false, length = 200)
    private String description;

    /**
     * Learning field that shows how many permissions this role owns.
     */
    @Column(nullable = false)
    private Integer permissionCount;

    /**
     * Comma-separated permission codes owned by this role.
     *
     * This is a learning-friendly storage shape. Later we can replace it with
     * a real many-to-many table such as sys_role_permission.
     */
    @Column(length = 200)
    private String permissionCodes;

    /**
     * Time when this role row was created.
     */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    /**
     * Time when this role row was last updated.
     */
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Runs before inserting a new row.
     */
    @PrePersist
    public void beforeCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Runs before updating an existing row.
     */
    @PreUpdate
    public void beforeUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getPermissionCount() {
        return permissionCount;
    }

    public void setPermissionCount(Integer permissionCount) {
        this.permissionCount = permissionCount;
    }

    public String getPermissionCodes() {
        return permissionCodes;
    }

    public void setPermissionCodes(String permissionCodes) {
        this.permissionCodes = permissionCodes;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
