package com.example.admin.role.repository;

import com.example.admin.role.entity.RoleEntity;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;
import java.util.Optional;

/**
 * Role database access layer.
 *
 * JpaRepository provides common database methods such as findAll, findById,
 * save and delete. The methods below are generated by Spring Data JPA from
 * their names.
 */
public interface RoleRepository extends JpaRepository<RoleEntity, Long> {

    /**
     * Query all roles and keep a stable order for the frontend table.
     */
    List<RoleEntity> findAllByOrderByIdAsc();

    /**
     * Query one role by its stable code.
     */
    Optional<RoleEntity> findByCode(String code);

    /**
     * Query one role by its display name.
     *
     * UserEntity.role currently stores this display name, so login needs this
     * method to find the role row and read its permission codes.
     */
    Optional<RoleEntity> findByName(String name);

    /**
     * Check whether one role code already exists.
     */
    boolean existsByCode(String code);
}
