package com.example.admin.user.service;

import com.example.admin.user.dto.CreateUserDTO;
import com.example.admin.user.dto.UpdateUserDTO;
import com.example.admin.user.vo.UserVO;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 * User business service.
 *
 * Service handles business logic. The project has not connected to a database
 * yet, so this class uses an in-memory list to simulate a user table.
 */
@Service
public class UserService {

    /**
     * In-memory user list.
     *
     * Data in this list exists only while the backend process is running.
     * After restarting the backend, it returns to the initial values below.
     */
    private static final List<UserVO> USERS = new ArrayList<UserVO>();

    /**
     * Next user ID.
     *
     * In real projects, IDs are usually generated by the database.
     */
    private static Long nextId = 4L;

    static {
        USERS.add(new UserVO(1L, "admin", "系统管理员", "超级管理员", "enabled"));
        USERS.add(new UserVO(2L, "manager", "运营经理", "运营管理员", "enabled"));
        USERS.add(new UserVO(3L, "auditor", "审计专员", "只读用户", "disabled"));
    }

    /**
     * Query all users.
     */
    public List<UserVO> listUsers() {
        return new ArrayList<UserVO>(USERS);
    }

    /**
     * Create a new user.
     */
    public UserVO createUser(CreateUserDTO createUserDTO) {
        UserVO user = new UserVO(
                nextId,
                createUserDTO.getUsername(),
                createUserDTO.getNickname(),
                createUserDTO.getRole(),
                createUserDTO.getStatus()
        );

        USERS.add(user);
        nextId = nextId + 1;

        return user;
    }

    /**
     * Update an existing user by ID.
     */
    public UserVO updateUser(Long id, UpdateUserDTO updateUserDTO) {
        for (UserVO user : USERS) {
            if (user.getId().equals(id)) {
                user.setUsername(updateUserDTO.getUsername());
                user.setNickname(updateUserDTO.getNickname());
                user.setRole(updateUserDTO.getRole());
                user.setStatus(updateUserDTO.getStatus());

                return user;
            }
        }

        return null;
    }

    /**
     * Delete a user by ID.
     *
     * Iterator lets us safely remove the current item while looping.
     */
    public boolean deleteUser(Long id) {
        Iterator<UserVO> iterator = USERS.iterator();

        while (iterator.hasNext()) {
            UserVO user = iterator.next();

            if (user.getId().equals(id)) {
                iterator.remove();
                return true;
            }
        }

        return false;
    }
}
